-- ============================================================
-- 004_jam_calendar_sync.sql
-- Schema for automatically importing games from the JAM Sports calendar
-- feed (an .ics URL). Run this file in the Supabase SQL Editor.
--
-- games.jam_uid: the stable per-game UID from the JAM .ics feed
-- (e.g. "game-90948@jamsports.com"). Once a game is linked to a jam_uid,
-- re-syncing recognizes it immediately (exact match) instead of relying on
-- the 30-minute fuzzy time window used only for games that predate this
-- importer (manually entered, no jam_uid yet).
--
-- jam_sync_conflicts: anything the importer can't confidently auto-create
-- lands here for manual review instead of silently creating a duplicate or
-- silently doing nothing:
--   - possible_duplicate / multiple_candidates: an existing game (no
--     jam_uid) was found on the same date within 30 minutes of the
--     incoming event's start time.
--   - no_season_match / multiple_season_match: couldn't find exactly one
--     Jam season whose date range covers the event date.
--   - unparseable: the feed's SUMMARY didn't match the expected
--     "<team> vs <opponent>" shape.
-- Resolution (via the app UI, using existing RLS-gated writes, not a
-- special endpoint): "Create" inserts a new games row from the stored
-- fields and sets status='created'; "Link" sets jam_uid on an existing
-- game and sets status='linked'; "Dismiss" sets status='dismissed'. Only
-- rows with status='pending' are re-surfaced; anything already resolved
-- (in any status) is left alone by future syncs so a dismissal sticks.
-- ============================================================

alter table public.games add column if not exists jam_uid text unique;

create table if not exists public.jam_sync_conflicts (
  id bigint generated by default as identity primary key,
  jam_uid text not null unique,
  opponent text not null,
  event_date date not null,
  event_time time not null,
  location text,
  existing_game_id integer references public.games(id) on delete set null,
  reason text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

-- Same public-read / team-write shape as every other table
-- (see 002_public_read_team_write.sql).
alter table public.jam_sync_conflicts enable row level security;

drop policy if exists "authenticated read" on public.jam_sync_conflicts;
create policy "authenticated read" on public.jam_sync_conflicts
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.jam_sync_conflicts;
create policy "team insert" on public.jam_sync_conflicts
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.jam_sync_conflicts;
create policy "team update" on public.jam_sync_conflicts
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.jam_sync_conflicts;
create policy "team delete" on public.jam_sync_conflicts
  for delete to authenticated
  using ((select public.is_allowed()));

-- No manual Vault step needed for the cron trigger itself: Vercel Cron Jobs
-- authenticate via its own CRON_SECRET convention (a plain Vercel env var
-- Vercel reads and auto-attaches as "Authorization: Bearer <value>" to cron
-- requests -- see https://vercel.com/docs/cron-jobs/manage-cron-jobs#securing-cron-jobs),
-- not Vault. Cloudflare's scheduled() trigger calls the sync function
-- in-process and isn't reachable over HTTP at all, so it needs no secret.
