-- ============================================================
-- 005_calendar_sources.sql
-- Generalizes the calendar importer (004_jam_calendar_sync.sql) from a
-- single hardcoded JAM Sports .ics URL to a table of calendar sources, one
-- per organizer. An organization is 1:1 with a calendar feed: adding a new
-- league (e.g. RHUC) is now a row in this table instead of a code change.
--
-- Run this file in the Supabase SQL Editor. Re-runnable.
--
-- MANUAL STEP (Supabase SQL editor) to add another calendar later:
--   insert into calendar_sources (organizer, calendar_url)
--   values ('RHUC', 'https://.../whatever.ics');
-- `organizer` must match the value used in seasons.organizer for that
-- league, since sync matches each source's events against seasons by
-- organizer (see gateway/jamSync.ts's runJamSync -> now iterates sources
-- instead of assuming 'Jam').
-- ============================================================

create table if not exists public.calendar_sources (
  id bigint generated by default as identity primary key,
  organizer text not null unique,
  calendar_url text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.calendar_sources (organizer, calendar_url)
values ('Jam', 'https://jamsports.com/api/calendar/12273c1d-6683-4d15-8c09-1934475c1e0b.ics')
on conflict (organizer) do nothing;

alter table public.calendar_sources enable row level security;

drop policy if exists "authenticated read" on public.calendar_sources;
create policy "authenticated read" on public.calendar_sources
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.calendar_sources;
create policy "team insert" on public.calendar_sources
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.calendar_sources;
create policy "team update" on public.calendar_sources
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.calendar_sources;
create policy "team delete" on public.calendar_sources
  for delete to authenticated
  using ((select public.is_allowed()));

-- Conflicts now need to say which calendar/organizer they came from, since
-- there can be more than one source once a second calendar is added.
alter table public.jam_sync_conflicts add column if not exists organizer text not null default 'Jam';
alter table public.jam_sync_conflicts alter column organizer drop default;
