-- ============================================================
-- 006_strategy_board.sql
-- Strategy board: named plays with free-position player placements.
--
-- The Strategy page shows an ultimate field where players (their
-- profile photos) are dragged to arbitrary positions, one layout per
-- named play. Coordinates are stored as fractions in [0, 1] of a
-- canonical LANDSCAPE field: x runs along the 100m length (0 = left
-- back line), y runs across the 37m width (0 = top sideline). The
-- frontend maps these to a portrait rendering on small screens.
--
-- Run this entire file in the Supabase SQL Editor AFTER 005.
-- Re-runnable (create table if not exists, drop policy if exists).
-- ============================================================

create table if not exists public.strategy_plays (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.strategy_positions (
  id bigint generated by default as identity primary key,
  play_id bigint not null references public.strategy_plays(id) on delete cascade,
  player_id integer not null references public.players(id) on delete cascade,
  x real not null check (x >= 0 and x <= 1),
  y real not null check (y >= 0 and y <= 1),
  created_at timestamptz not null default now(),
  unique (play_id, player_id)
);

-- Same public-read / team-write shape as every other table
-- (see 002_public_read_team_write.sql).
alter table public.strategy_plays enable row level security;

drop policy if exists "authenticated read" on public.strategy_plays;
create policy "authenticated read" on public.strategy_plays
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.strategy_plays;
create policy "team insert" on public.strategy_plays
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.strategy_plays;
create policy "team update" on public.strategy_plays
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.strategy_plays;
create policy "team delete" on public.strategy_plays
  for delete to authenticated
  using ((select public.is_allowed()));

alter table public.strategy_positions enable row level security;

drop policy if exists "authenticated read" on public.strategy_positions;
create policy "authenticated read" on public.strategy_positions
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.strategy_positions;
create policy "team insert" on public.strategy_positions
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.strategy_positions;
create policy "team update" on public.strategy_positions
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.strategy_positions;
create policy "team delete" on public.strategy_positions
  for delete to authenticated
  using ((select public.is_allowed()));
