-- ============================================================
-- 007_strategy_arrows.sql
-- Strategy board arrows: freeform annotations that diagram player
-- movement and cuts, one set per play. Arrows are NOT tied to a
-- player. Each arrow is a quadratic Bezier: a start point (x1, y1),
-- an end point (x2, y2), and a control point (cx, cy). A straight
-- arrow stores cx,cy at the midpoint of the endpoints; bending moves
-- the control point.
--
-- Coordinates are fractions in [0, 1] of the canonical LANDSCAPE
-- field, the same frame as strategy_positions (x along the 100m
-- length, y across the 37m width). The frontend maps these to the
-- portrait rendering on small screens.
--
-- Run this entire file in the Supabase SQL Editor AFTER 006.
-- Re-runnable (create table if not exists, drop policy if exists).
-- ============================================================

create table if not exists public.strategy_arrows (
  id bigint generated by default as identity primary key,
  play_id bigint not null references public.strategy_plays(id) on delete cascade,
  x1 real not null check (x1 >= 0 and x1 <= 1),
  y1 real not null check (y1 >= 0 and y1 <= 1),
  x2 real not null check (x2 >= 0 and x2 <= 1),
  y2 real not null check (y2 >= 0 and y2 <= 1),
  cx real not null check (cx >= 0 and cx <= 1),
  cy real not null check (cy >= 0 and cy <= 1),
  created_at timestamptz not null default now()
);

create index if not exists strategy_arrows_play_id_idx
  on public.strategy_arrows (play_id);

-- Same public-read / team-write shape as every other table
-- (see 002_public_read_team_write.sql and 006_strategy_board.sql).
alter table public.strategy_arrows enable row level security;

drop policy if exists "authenticated read" on public.strategy_arrows;
create policy "authenticated read" on public.strategy_arrows
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.strategy_arrows;
create policy "team insert" on public.strategy_arrows
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.strategy_arrows;
create policy "team update" on public.strategy_arrows
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.strategy_arrows;
create policy "team delete" on public.strategy_arrows
  for delete to authenticated
  using ((select public.is_allowed()));
