-- ============================================================
-- 007_strategy_multi_step.sql
-- Expands the Strategy board from one static layout per play into:
--   - a play optionally tied to a game (so the bench can be filtered to
--     that game's attendees)
--   - an ordered sequence of steps per play (strategy_steps), so a play can
--     be stepped through with Prev/Next; positions become step-scoped
--     instead of play-scoped
--   - unnamed opponent markers per step (strategy_opponent_markers)
--   - freeform arrows per step (strategy_arrows), each either a 'run' (cut)
--     or a 'throw' (pass)
--
-- This rescopes the already-shipped strategy_positions table from play_id
-- to step_id. The data in it is effectively test-only, so a single-step
-- backfill (one step per existing play) is safe rather than a phased
-- migration.
--
-- Run this entire file in the Supabase SQL Editor AFTER 006.
-- Re-runnable (create table if not exists, add column if not exists, drop
-- policy if exists), except the backfill/constraint-swap statements which
-- are idempotent via "where ... is null" / "if exists" guards.
-- ============================================================

alter table public.strategy_plays
  add column if not exists game_id bigint references public.games(id) on delete set null;

create table if not exists public.strategy_steps (
  id bigint generated by default as identity primary key,
  play_id bigint not null references public.strategy_plays(id) on delete cascade,
  step_number integer not null,
  created_at timestamptz not null default now(),
  unique (play_id, step_number)
);

-- Backfill: one step per existing play.
insert into public.strategy_steps (play_id, step_number)
select p.id, 1 from public.strategy_plays p
where not exists (select 1 from public.strategy_steps s where s.play_id = p.id);

-- Rescope strategy_positions from play_id to step_id.
alter table public.strategy_positions add column if not exists step_id bigint references public.strategy_steps(id) on delete cascade;

update public.strategy_positions p
set step_id = s.id
from public.strategy_steps s
where s.play_id = p.play_id and s.step_number = 1 and p.step_id is null;

alter table public.strategy_positions alter column step_id set not null;
alter table public.strategy_positions drop constraint if exists strategy_positions_play_id_player_id_key;
alter table public.strategy_positions drop constraint if exists strategy_positions_step_id_player_id_key;
alter table public.strategy_positions add constraint strategy_positions_step_id_player_id_key unique (step_id, player_id);
alter table public.strategy_positions drop column if exists play_id;

create table if not exists public.strategy_opponent_markers (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.strategy_steps(id) on delete cascade,
  label text not null,
  x real not null check (x >= 0 and x <= 1),
  y real not null check (y >= 0 and y <= 1),
  created_at timestamptz not null default now()
);

create table if not exists public.strategy_arrows (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.strategy_steps(id) on delete cascade,
  arrow_type text not null default 'run' check (arrow_type in ('run', 'throw')),
  x1 real not null check (x1 >= 0 and x1 <= 1),
  y1 real not null check (y1 >= 0 and y1 <= 1),
  x2 real not null check (x2 >= 0 and x2 <= 1),
  y2 real not null check (y2 >= 0 and y2 <= 1),
  cx real not null check (cx >= 0 and cx <= 1),
  cy real not null check (cy >= 0 and cy <= 1),
  created_at timestamptz not null default now()
);

-- Same public-read / team-write shape as every other table
-- (see 002_public_read_team_write.sql).
alter table public.strategy_steps enable row level security;

drop policy if exists "authenticated read" on public.strategy_steps;
create policy "authenticated read" on public.strategy_steps
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.strategy_steps;
create policy "team insert" on public.strategy_steps
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.strategy_steps;
create policy "team update" on public.strategy_steps
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.strategy_steps;
create policy "team delete" on public.strategy_steps
  for delete to authenticated
  using ((select public.is_allowed()));

alter table public.strategy_opponent_markers enable row level security;

drop policy if exists "authenticated read" on public.strategy_opponent_markers;
create policy "authenticated read" on public.strategy_opponent_markers
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.strategy_opponent_markers;
create policy "team insert" on public.strategy_opponent_markers
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.strategy_opponent_markers;
create policy "team update" on public.strategy_opponent_markers
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.strategy_opponent_markers;
create policy "team delete" on public.strategy_opponent_markers
  for delete to authenticated
  using ((select public.is_allowed()));

alter table public.strategy_arrows enable row level security;

drop policy if exists "authenticated read" on public.strategy_arrows;
create policy "authenticated read" on public.strategy_arrows
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.strategy_arrows;
create policy "team insert" on public.strategy_arrows
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.strategy_arrows;
create policy "team update" on public.strategy_arrows
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.strategy_arrows;
create policy "team delete" on public.strategy_arrows
  for delete to authenticated
  using ((select public.is_allowed()));
