-- ============================================================
-- 010_league_tracking.sql
-- League tracking: opponents as entities, full league schedule,
-- auto-computed standings inputs, playoff bracket structure.
--
-- Model:
-- - league_teams: one row per team per season, including our own
--   team (flagged is_us, at most one per season). Opponent notes
--   (scouting) live here.
-- - league_games: the canonical league schedule and bracket. Every
--   matchup in the league is a row, including our own games. A
--   matchup we play in links to its rich games row via our_game_id
--   and stores NO score of its own: the app derives the score from
--   that game's goal events (single source of truth). Matchups we
--   are not in store home_score/away_score directly and are marked
--   final by setting status.
-- - Playoff games carry round/bracket_pos plus next_game_id and
--   next_slot ('home'|'away') pointers; the app writes the winner
--   into the next game's open slot when a result is recorded.
-- - seasons gain win_points/tie_points/loss_points (default 2/1/0)
--   so standings math is per-league configurable.
-- - games.opponent_team_id links a game to its league team. The
--   legacy games.opponent text column remains the way opponents are
--   entered; triggers below resolve it to a league_teams row and keep
--   the paired league_games row in sync on every insert/update/delete,
--   so every creation path (app, Jam calendar sync, manual SQL) upholds
--   the pairing invariant with no application plumbing.
-- - The old public.standings table is deprecated: nothing reads or
--   writes it. Standings are computed from league_games.
--
-- Run this entire file in the Supabase SQL Editor AFTER 009.
-- Re-runnable (create table if not exists, drop policy if exists).
-- ============================================================

-- ---------- Tables ----------

create table if not exists public.league_teams (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  name text not null,
  is_us boolean not null default false,
  color text,
  notes text,
  created_at timestamptz not null default now(),
  unique (season_id, name)
);

-- At most one "us" row per season.
create unique index if not exists league_teams_one_us_per_season
  on public.league_teams (season_id) where is_us;

create table if not exists public.league_games (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  home_team_id bigint references public.league_teams(id) on delete set null,
  away_team_id bigint references public.league_teams(id) on delete set null,
  home_score integer,
  away_score integer,
  game_date date,
  game_time time,
  location text,
  stage text not null default 'regular' check (stage in ('regular', 'playoff')),
  round text,
  bracket_pos integer,
  next_game_id bigint references public.league_games(id) on delete set null,
  next_slot text check (next_slot in ('home', 'away')),
  our_game_id bigint unique references public.games(id) on delete set null,
  status text not null default 'scheduled' check (status in ('scheduled', 'final')),
  created_at timestamptz not null default now()
);

create index if not exists league_games_season_idx on public.league_games (season_id);

alter table public.games
  add column if not exists opponent_team_id bigint references public.league_teams(id) on delete set null;

alter table public.seasons
  add column if not exists win_points integer not null default 2,
  add column if not exists tie_points integer not null default 1,
  add column if not exists loss_points integer not null default 0;

-- ---------- RLS ----------
-- Same public-read / team-write shape as every other table
-- (see 002_public_read_team_write.sql).

alter table public.league_teams enable row level security;

drop policy if exists "authenticated read" on public.league_teams;
create policy "authenticated read" on public.league_teams
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.league_teams;
create policy "team insert" on public.league_teams
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.league_teams;
create policy "team update" on public.league_teams
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.league_teams;
create policy "team delete" on public.league_teams
  for delete to authenticated
  using ((select public.is_allowed()));

alter table public.league_games enable row level security;

drop policy if exists "authenticated read" on public.league_games;
create policy "authenticated read" on public.league_games
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.league_games;
create policy "team insert" on public.league_games
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.league_games;
create policy "team update" on public.league_games
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.league_games;
create policy "team delete" on public.league_games
  for delete to authenticated
  using ((select public.is_allowed()));

-- ---------- Backfill ----------
-- 1. One is_us league_team per season that has games, named after the
--    season's team (falls back to 'Warriors' if the join is empty).
insert into public.league_teams (season_id, name, is_us)
select s.id, coalesce(t.name, 'Warriors'), true
from public.seasons s
left join public.teams t on t.id = s.team_id
where exists (select 1 from public.games g where g.season_id = s.id)
  and not exists (
    select 1 from public.league_teams lt
    where lt.season_id = s.id and lt.is_us
  );

-- 2. One league_team per distinct opponent name per season.
insert into public.league_teams (season_id, name)
select distinct g.season_id, trim(g.opponent)
from public.games g
where g.season_id is not null
  and g.opponent is not null
  and trim(g.opponent) <> ''
on conflict (season_id, name) do nothing;

-- 3. Link games to their opponent league_team by name.
update public.games g
set opponent_team_id = lt.id
from public.league_teams lt
where g.opponent_team_id is null
  and lt.season_id = g.season_id
  and lt.is_us = false
  and lt.name = trim(g.opponent);

-- 4. A paired league_games row for every existing game (home = us).
--    Scores stay null: the app derives them from the linked game.
insert into public.league_games
  (season_id, home_team_id, away_team_id, game_date, game_time, stage, our_game_id)
select
  g.season_id,
  us.id,
  g.opponent_team_id,
  g.game_date,
  g.game_time,
  case when g.game_type ilike 'playoff%' then 'playoff' else 'regular' end,
  g.id
from public.games g
join public.league_teams us on us.season_id = g.season_id and us.is_us
where g.season_id is not null
  and not exists (
    select 1 from public.league_games lg where lg.our_game_id = g.id
  );

-- ---------- Triggers: games to league_games pairing ----------
-- Created AFTER the backfill so it does not fire mid-backfill.

-- Resolve the opponent text to a league_teams row (creating it on first
-- mention) before a game is written.
create or replace function public.resolve_game_opponent_team()
returns trigger
language plpgsql
as $$
declare
  v_name text := nullif(trim(coalesce(new.opponent, '')), '');
begin
  if new.season_id is null or v_name is null then
    return new;
  end if;
  -- Keep an explicit assignment if it already points at a team in this
  -- season; otherwise re-resolve from the opponent text.
  if new.opponent_team_id is not null and exists (
    select 1 from public.league_teams lt
    where lt.id = new.opponent_team_id and lt.season_id = new.season_id
  ) then
    return new;
  end if;
  insert into public.league_teams (season_id, name)
  values (new.season_id, v_name)
  on conflict (season_id, name) do nothing;
  select id into new.opponent_team_id
  from public.league_teams
  where season_id = new.season_id and name = v_name;
  return new;
end
$$;

-- Maintain the paired league_games row. Idempotent upsert-by-our_game_id,
-- so it self-heals a missing pair on the next touch of the game.
create or replace function public.sync_game_league_pair()
returns trigger
language plpgsql
as $$
declare
  v_us bigint;
  v_stage text;
begin
  if tg_op = 'DELETE' then
    delete from public.league_games where our_game_id = old.id;
    return old;
  end if;
  if new.season_id is null then
    delete from public.league_games where our_game_id = new.id;
    return new;
  end if;

  -- Ensure our own league team exists for this season.
  insert into public.league_teams (season_id, name, is_us)
  select s.id, coalesce(t.name, 'Warriors'), true
  from public.seasons s
  left join public.teams t on t.id = s.team_id
  where s.id = new.season_id
  on conflict do nothing;

  select id into v_us
  from public.league_teams
  where season_id = new.season_id and is_us;

  v_stage := case when new.game_type ilike 'playoff%' then 'playoff' else 'regular' end;

  update public.league_games set
    season_id = new.season_id,
    home_team_id = v_us,
    away_team_id = new.opponent_team_id,
    game_date = new.game_date,
    game_time = new.game_time,
    stage = v_stage
  where our_game_id = new.id;
  if not found then
    insert into public.league_games
      (season_id, home_team_id, away_team_id, game_date, game_time, stage, our_game_id)
    values
      (new.season_id, v_us, new.opponent_team_id, new.game_date, new.game_time, v_stage, new.id);
  end if;
  return new;
end
$$;

drop trigger if exists games_resolve_opponent_team on public.games;
create trigger games_resolve_opponent_team
  before insert or update on public.games
  for each row execute function public.resolve_game_opponent_team();

drop trigger if exists games_sync_league_pair on public.games;
create trigger games_sync_league_pair
  after insert or update on public.games
  for each row execute function public.sync_game_league_pair();

drop trigger if exists games_delete_league_pair on public.games;
create trigger games_delete_league_pair
  after delete on public.games
  for each row execute function public.sync_game_league_pair();
