-- Adds free-floating text-box annotations to the Strategy board, alongside
-- players/opponent markers/arrows. Step-scoped and structurally identical
-- to strategy_opponent_markers (no roster backing, no persistent cross-step
-- identity), but holds freeform text instead of an auto-numbered label.

create table if not exists public.strategy_text_boxes (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.strategy_steps(id) on delete cascade,
  text text not null default '',
  x real not null check (x >= 0 and x <= 1),
  y real not null check (y >= 0 and y <= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text
);

drop trigger if exists strategy_text_boxes_audit on public.strategy_text_boxes;
create trigger strategy_text_boxes_audit before insert or update on public.strategy_text_boxes
  for each row execute function public.set_audit_fields();

-- Same public-read / team-write shape as every other strategy table
-- (see 002_public_read_team_write.sql, 007_strategy_multi_step.sql).
alter table public.strategy_text_boxes enable row level security;

drop policy if exists "authenticated read" on public.strategy_text_boxes;
create policy "authenticated read" on public.strategy_text_boxes
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.strategy_text_boxes;
create policy "team insert" on public.strategy_text_boxes
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.strategy_text_boxes;
create policy "team update" on public.strategy_text_boxes
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.strategy_text_boxes;
create policy "team delete" on public.strategy_text_boxes
  for delete to authenticated
  using ((select public.is_allowed()));
