-- Adds explicit persistence + ordering for lineup GROUPS (e.g. "Lineup 1",
-- "Handlers"), distinct from game_lineups.sort_order which only orders the
-- players *within* a group. Previously a lineup group's existence was purely
-- implicit: it only "existed" once it had at least one game_lineups row, so
-- a newly-named lineup with no players yet had nothing to show and no way
-- to be reordered against the others.

create table if not exists public.game_lineup_groups (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  lineup_name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text,
  unique (game_id, lineup_name)
);

drop trigger if exists game_lineup_groups_audit on public.game_lineup_groups;
create trigger game_lineup_groups_audit before insert or update on public.game_lineup_groups
  for each row execute function public.set_audit_fields();

-- Same public-read / team-write shape as every other table (see
-- 002_public_read_team_write.sql, 007_strategy_multi_step.sql).
alter table public.game_lineup_groups enable row level security;

drop policy if exists "authenticated read" on public.game_lineup_groups;
create policy "authenticated read" on public.game_lineup_groups
  for select to authenticated
  using (true);

drop policy if exists "team insert" on public.game_lineup_groups;
create policy "team insert" on public.game_lineup_groups
  for insert to authenticated
  with check ((select public.is_allowed()));

drop policy if exists "team update" on public.game_lineup_groups;
create policy "team update" on public.game_lineup_groups
  for update to authenticated
  using ((select public.is_allowed()))
  with check ((select public.is_allowed()));

drop policy if exists "team delete" on public.game_lineup_groups;
create policy "team delete" on public.game_lineup_groups
  for delete to authenticated
  using ((select public.is_allowed()));

-- Backfill: every game that already has lineup entries gets a group row for
-- each of its existing distinct lineup_name values, ordered by first
-- appearance (lowest game_lineups.id within that group).
insert into public.game_lineup_groups (game_id, lineup_name, sort_order)
select game_id, lineup_name, row_number() over (partition by game_id order by min(id)) - 1
from public.game_lineups
group by game_id, lineup_name
on conflict (game_id, lineup_name) do nothing;

-- Per-lineup role/position for a player (e.g. "Handler", "Deep"), distinct
-- from players.position (their general roster position tag): the same
-- player can play a different role in different lineups/games. Named role,
-- not position, for the same reason sort_order wasn't named position in
-- 013_game_lineups_sort_order.sql: game_lineups rows are joined with
-- players(position) and flattened onto the same client-side object, so a
-- column literally named position would collide with it.
alter table public.game_lineups add column if not exists role text;
