-- ============================================================
-- 016_organizations.sql
-- Multi-tenant migration: introduces `organizations` as the real tenant
-- boundary, replacing the single global `allowed_users` email allowlist.
--
-- Naming note: `teams` already means "squad name for a season/league"
-- (e.g. "Disc-iples", "Jogging Dead") -- the same friend group plays under
-- several team names across leagues/seasons and shares one roster via
-- season_players. `organizations` sits above that: a real person or group
-- signs up, creates (or is invited into) exactly one or more organizations,
-- and every team/season/game/player/etc. belongs to exactly one
-- organization. Signup itself stays open (unauthenticated Supabase Auth
-- signup was never gated -- only writes were); a user with zero
-- organization memberships creates one on first login (app-side flow).
--
-- Run this entire file in the Supabase SQL Editor AFTER 015.
-- ============================================================

-- ------------------------------------------------------------
-- 1. organizations + organization_members
-- ------------------------------------------------------------
create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text
);

drop trigger if exists organizations_audit on public.organizations;
create trigger organizations_audit before insert or update on public.organizations
  for each row execute function public.set_audit_fields();

create table if not exists public.organization_members (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  email text not null check (email = lower(email)),
  role text not null default 'member' check (role in ('owner', 'member')),
  created_at timestamptz not null default now(),
  unique (organization_id, email)
);

-- ------------------------------------------------------------
-- 2. Helper functions (SECURITY DEFINER, mirroring is_allowed()).
-- ------------------------------------------------------------
create or replace function public.is_org_member(org_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.organization_members
    where organization_id = org_id
      and email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_org_member(bigint) from public, anon;
grant execute on function public.is_org_member(bigint) to authenticated;

create or replace function public.is_org_owner(org_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.organization_members
    where organization_id = org_id
      and role = 'owner'
      and email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_org_owner(bigint) from public, anon;
grant execute on function public.is_org_owner(bigint) to authenticated;

create or replace function public.org_is_public(org_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select is_public from public.organizations where id = org_id), false);
$$;

revoke all on function public.org_is_public(bigint) from public, anon;
grant execute on function public.org_is_public(bigint) to authenticated;

-- One-call fetch of the caller's org memberships, for the auth gateway's
-- session endpoint (replaces checkAllowed()'s is_allowed() RPC call).
create or replace function public.my_organizations()
returns table (organization_id bigint, name text, role text, is_public boolean)
language sql
stable
security definer
set search_path = ''
as $$
  select o.id, o.name, m.role, o.is_public
  from public.organization_members m
  join public.organizations o on o.id = m.organization_id
  where m.email = lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

revoke all on function public.my_organizations() from public, anon;
grant execute on function public.my_organizations() to authenticated;

-- ------------------------------------------------------------
-- 3. RLS for organizations / organization_members themselves.
-- ------------------------------------------------------------
alter table public.organizations enable row level security;

drop policy if exists "member or public read" on public.organizations;
create policy "member or public read" on public.organizations
  for select to authenticated
  using ((select public.is_org_member(id)) or is_public);

drop policy if exists "any signed-in insert" on public.organizations;
create policy "any signed-in insert" on public.organizations
  for insert to authenticated
  with check (true);

drop policy if exists "owner update" on public.organizations;
create policy "owner update" on public.organizations
  for update to authenticated
  using ((select public.is_org_owner(id)))
  with check ((select public.is_org_owner(id)));

drop policy if exists "owner delete" on public.organizations;
create policy "owner delete" on public.organizations
  for delete to authenticated
  using ((select public.is_org_owner(id)));

alter table public.organization_members enable row level security;

drop policy if exists "member read" on public.organization_members;
create policy "member read" on public.organization_members
  for select to authenticated
  using ((select public.is_org_member(organization_id)));

-- Creating the very first (owner) row for a brand-new organization can't
-- go through is_org_owner (no rows exist yet), so allow a signed-in user
-- to insert a row for themselves; anyone else being invited still requires
-- the inserting caller to already own the org.
drop policy if exists "owner invite or self join" on public.organization_members;
create policy "owner invite or self join" on public.organization_members
  for insert to authenticated
  with check (
    (select public.is_org_owner(organization_id))
    or email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

drop policy if exists "owner update role" on public.organization_members;
create policy "owner update role" on public.organization_members
  for update to authenticated
  using ((select public.is_org_owner(organization_id)))
  with check ((select public.is_org_owner(organization_id)));

-- Owners can remove anyone; anyone can remove their own membership (leave).
drop policy if exists "owner remove or self leave" on public.organization_members;
create policy "owner remove or self leave" on public.organization_members
  for delete to authenticated
  using (
    (select public.is_org_owner(organization_id))
    or email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

revoke all on public.organizations from anon;
revoke all on public.organization_members from anon;

-- ------------------------------------------------------------
-- 4. organization_id on every domain table (denormalized: every table
--    carries its own copy rather than being derived via a join chain, so
--    every RLS policy below is a flat is_org_member(organization_id)
--    check -- same shape as is_allowed() was). Excludes event_types
--    (shared global reference data) and standings (deprecated, unused).
--    game_attendance/chat_logs have no tracked `create table` anywhere in
--    this repo (created ad hoc in the live DB) -- `alter table if exists`
--    is correct whether or not they're present.
-- ------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'teams', 'seasons', 'players', 'games', 'game_events',
    'season_players', 'game_lineups', 'game_lineup_groups',
    'game_attendance', 'league_teams', 'league_games',
    'strategy_plays', 'strategy_steps', 'strategy_positions',
    'strategy_opponent_markers', 'strategy_arrows', 'strategy_text_boxes',
    'calendar_sources', 'jam_sync_conflicts', 'chat_logs'
  ]
  loop
    if to_regclass('public.' || t) is null then
      raise notice 'skipping missing table: %', t;
      continue;
    end if;
    execute format(
      'alter table public.%I add column if not exists organization_id bigint references public.organizations(id) on delete cascade',
      t
    );
  end loop;
end
$$;

-- ------------------------------------------------------------
-- 5. Backfill: one organization for all existing data, owned by the
--    current user, with every existing allowlisted teammate carried over
--    as a member so nobody loses write access.
-- ------------------------------------------------------------
do $$
declare
  v_org_id bigint;
  t text;
  v_email text;
begin
  insert into public.organizations (name, is_public)
  values ('My Team', false)
  returning id into v_org_id;

  insert into public.organization_members (organization_id, email, role)
  values (v_org_id, 'eric@venn.ca', 'owner')
  on conflict (organization_id, email) do nothing;

  if to_regclass('public.allowed_users') is not null then
    for v_email in select email from public.allowed_users loop
      insert into public.organization_members (organization_id, email, role)
      values (v_org_id, v_email, 'member')
      on conflict (organization_id, email) do nothing;
    end loop;
  end if;

  foreach t in array array[
    'teams', 'seasons', 'players', 'games', 'game_events',
    'season_players', 'game_lineups', 'game_lineup_groups',
    'game_attendance', 'league_teams', 'league_games',
    'strategy_plays', 'strategy_steps', 'strategy_positions',
    'strategy_opponent_markers', 'strategy_arrows', 'strategy_text_boxes',
    'calendar_sources', 'jam_sync_conflicts', 'chat_logs'
  ]
  loop
    if to_regclass('public.' || t) is null then
      continue;
    end if;
    execute format('update public.%I set organization_id = %L where organization_id is null', t, v_org_id);
    execute format('alter table public.%I alter column organization_id set not null', t);
  end loop;
end
$$;

-- ------------------------------------------------------------
-- 6. Rewrite RLS on every org-scoped table: read = member or public org,
--    write = member. Same do-block-per-table pattern as 001/002, with
--    is_org_member(organization_id) in place of is_allowed().
-- ------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'teams', 'seasons', 'players', 'games', 'game_events',
    'season_players', 'game_lineups', 'game_lineup_groups',
    'game_attendance', 'league_teams', 'league_games',
    'strategy_plays', 'strategy_steps', 'strategy_positions',
    'strategy_opponent_markers', 'strategy_arrows', 'strategy_text_boxes',
    'calendar_sources', 'jam_sync_conflicts', 'chat_logs'
  ]
  loop
    if to_regclass('public.' || t) is null then
      continue;
    end if;

    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists "allowlisted full access" on public.%I', t);
    execute format('drop policy if exists "authenticated read" on public.%I', t);
    execute format('drop policy if exists "team insert" on public.%I', t);
    execute format('drop policy if exists "team update" on public.%I', t);
    execute format('drop policy if exists "team delete" on public.%I', t);

    execute format(
      'create policy "org member or public read" on public.%I
         for select to authenticated
         using ((select public.is_org_member(organization_id)) or (select public.org_is_public(organization_id)))',
      t
    );
    execute format(
      'create policy "org member insert" on public.%I
         for insert to authenticated
         with check ((select public.is_org_member(organization_id)))',
      t
    );
    execute format(
      'create policy "org member update" on public.%I
         for update to authenticated
         using ((select public.is_org_member(organization_id)))
         with check ((select public.is_org_member(organization_id)))',
      t
    );
    execute format(
      'create policy "org member delete" on public.%I
         for delete to authenticated
         using ((select public.is_org_member(organization_id)))',
      t
    );
  end loop;
end
$$;

-- event_types (shared global reference data, no organization_id) and
-- standings (deprecated, unused) still carry is_allowed()-referencing
-- write policies from 002_public_read_team_write.sql. Those must be
-- dropped (or replaced) before is_allowed() itself can be dropped below.
-- event_types keeps write access for any signed-in org member (global,
-- not org-scoped, since event type categories are shared across every
-- organization); standings just loses its write policies outright since
-- nothing reads or writes it.
drop policy if exists "team insert" on public.event_types;
create policy "org member insert" on public.event_types
  for insert to authenticated
  with check (exists (
    select 1 from public.organization_members
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  ));

drop policy if exists "team update" on public.event_types;
create policy "org member update" on public.event_types
  for update to authenticated
  using (exists (
    select 1 from public.organization_members
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  ))
  with check (exists (
    select 1 from public.organization_members
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  ));

drop policy if exists "team delete" on public.event_types;
create policy "org member delete" on public.event_types
  for delete to authenticated
  using (exists (
    select 1 from public.organization_members
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  ));

drop policy if exists "team insert" on public.standings;
drop policy if exists "team update" on public.standings;
drop policy if exists "team delete" on public.standings;
drop policy if exists "allowlisted full access" on public.standings;

-- Storage: player-photos writes gated on membership in the org that owns
-- the player being photographed isn't practical to check from a storage
-- policy (the bucket has no path convention tying an object to a player).
-- Keep this bucket allowlisted-by-any-org-member instead: any signed-in
-- user who belongs to at least one organization may write, matching the
-- low-stakes nature of a public-read photo bucket.
drop policy if exists "allowlisted insert player photos" on storage.objects;
create policy "org member insert player photos" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'player-photos' and exists (
    select 1 from public.organization_members
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  ));

drop policy if exists "allowlisted update player photos" on storage.objects;
create policy "org member update player photos" on storage.objects
  for update to authenticated
  using (bucket_id = 'player-photos' and exists (
    select 1 from public.organization_members
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  ))
  with check (bucket_id = 'player-photos' and exists (
    select 1 from public.organization_members
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  ));

drop policy if exists "allowlisted delete player photos" on storage.objects;
create policy "org member delete player photos" on storage.objects
  for delete to authenticated
  using (bucket_id = 'player-photos' and exists (
    select 1 from public.organization_members
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  ));

-- ------------------------------------------------------------
-- 7. Drop the now-fully-superseded global allowlist. Must land in the
--    same deploy as the gateway/auth-handlers.ts and server/index.ts
--    changes that stop calling is_allowed()/querying allowed_users.
-- ------------------------------------------------------------
drop function if exists public.is_allowed();
drop table if exists public.allowed_users;
