-- ============================================================
-- 019_lineup_templates.sql
-- Named, reusable lineup templates: save a game's current lineup
-- (group names + player assignments) as a named template scoped to a
-- season, then load it into any other game in that season later. This
-- is independent of game order — unlike "Copy Last Game's Lineup"
-- (which always copies the immediately-previous game), a template can
-- be saved once (e.g. "Standard Lines") and reused indefinitely.
--
-- Mirrors game_lineup_groups/game_lineups' shape (a group is its own
-- row, a player's group membership is a plain lineup_name text match,
-- not a group foreign key — same rationale as 015_game_lineup_groups.sql:
-- an empty group with zero players placed should still exist/render/be
-- orderable).
--
-- Run this entire file in the Supabase SQL Editor AFTER 018.
-- Re-runnable (create table if not exists, drop policy if exists).
-- ============================================================

create table if not exists public.lineup_templates (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  season_id bigint not null references public.seasons(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text,
  unique (season_id, name)
);

create table if not exists public.lineup_template_groups (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.lineup_templates(id) on delete cascade,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  lineup_name text not null,
  sort_order integer not null default 0,
  unique (template_id, lineup_name)
);

create table if not exists public.lineup_template_players (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.lineup_templates(id) on delete cascade,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  lineup_name text not null,
  player_id integer not null references public.players(id) on delete cascade,
  sort_order integer not null default 0,
  role text
);

drop trigger if exists lineup_templates_audit on public.lineup_templates;
create trigger lineup_templates_audit before insert or update on public.lineup_templates
  for each row execute function public.set_audit_fields();

-- Same any-authenticated read/write shape as every other table under the
-- soft-launch access model (see 017_open_access_for_now.sql).
do $$
declare
  t text;
begin
  foreach t in array array['lineup_templates', 'lineup_template_groups', 'lineup_template_players']
  loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists "authenticated read" on public.%I', t);
    execute format('create policy "authenticated read" on public.%I for select to authenticated using (true)', t);

    execute format('drop policy if exists "authenticated insert" on public.%I', t);
    execute format('create policy "authenticated insert" on public.%I for insert to authenticated with check (true)', t);

    execute format('drop policy if exists "authenticated update" on public.%I', t);
    execute format('create policy "authenticated update" on public.%I for update to authenticated using (true) with check (true)', t);

    execute format('drop policy if exists "authenticated delete" on public.%I', t);
    execute format('create policy "authenticated delete" on public.%I for delete to authenticated using (true)', t);
  end loop;
end
$$;
