-- Adds freehand highlighted zones to the Strategy board, alongside
-- players/opponent markers/arrows/text boxes. Step-scoped and
-- structurally similar to strategy_text_boxes (no roster backing, no
-- persistent cross-step identity, drag-off-field deletes it), but holds a
-- freeform filled shape instead of a point: `points` is a JSON array of
-- {x, y} vertices (same canonical [0,1] field-fraction coordinates as
-- every other strategy table), traced out by a drag gesture and closed
-- into a polygon on release. Used for things a single arrow or text box
-- can't express well: a throwing lane, a zone to attack, a force
-- direction's cone.
--
-- Run this entire file in the Supabase SQL Editor AFTER 023.

-- organization_id is required (see "Multi-tenancy: organizations" in
-- CLAUDE.md: every domain table carries a denormalized organization_id,
-- app code sets it explicitly at insert time). Every other strategy_*
-- table already carries it live even though the older migration files
-- that created them predate that convention; matching that here.
create table if not exists public.strategy_highlights (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.strategy_steps(id) on delete cascade,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  points jsonb not null check (jsonb_typeof(points) = 'array' and jsonb_array_length(points) >= 3),
  color text not null default '#f59e0b',
  -- Whether this was drawn with the tap-to-place Straight tool rather than
  -- freehand: a straight-drawn shape's corners are individually draggable
  -- in the UI (each vertex is a deliberate tap), a freehand trace's are not
  -- (hundreds of samples, editing one point at a time isn't useful there).
  is_straight boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text
);

-- Re-running this file against a deployment where strategy_highlights was
-- already created by an earlier version of this same migration (before
-- is_straight existed) needs this explicitly: `create table if not exists`
-- above is a no-op once the table exists, so it would never pick up a
-- column added to the definition after the fact without this.
alter table public.strategy_highlights add column if not exists is_straight boolean not null default false;

drop trigger if exists strategy_highlights_audit on public.strategy_highlights;
create trigger strategy_highlights_audit before insert or update on public.strategy_highlights
  for each row execute function public.set_audit_fields();

-- Same shape as every other strategy_* table's *live* policies (not the
-- is_allowed()-wrapped ones in the older migration files, which predate
-- 017_open_access_for_now.sql's relaxation and no longer match what's
-- actually deployed): plain "true" for every authenticated action.
alter table public.strategy_highlights enable row level security;

drop policy if exists "authenticated read" on public.strategy_highlights;
create policy "authenticated read" on public.strategy_highlights
  for select to authenticated
  using (true);

drop policy if exists "authenticated insert" on public.strategy_highlights;
create policy "authenticated insert" on public.strategy_highlights
  for insert to authenticated
  with check (true);

drop policy if exists "authenticated update" on public.strategy_highlights;
create policy "authenticated update" on public.strategy_highlights
  for update to authenticated
  using (true)
  with check (true);

drop policy if exists "authenticated delete" on public.strategy_highlights;
create policy "authenticated delete" on public.strategy_highlights
  for delete to authenticated
  using (true);

-- Bump the parent play's updated_at when a highlight changes too (see
-- 018_strategy_play_touch.sql; touch_strategy_play works for any table
-- with a step_id column, so this just attaches it to the new one).
drop trigger if exists strategy_highlights_touch_play on public.strategy_highlights;
create trigger strategy_highlights_touch_play after insert or update or delete on public.strategy_highlights
  for each row execute function public.touch_strategy_play();
