-- Adds plain unfilled lines to the Strategy board: a freehand pencil stroke
-- or a tap-to-place straight-corner line, distinct from strategy_highlights
-- (always a closed filled zone) and from strategy_arrows (always has an
-- arrowhead, can anchor to a player/opponent). Step-scoped and structurally
-- almost identical to strategy_highlights: `points` is a JSON array of
-- {x, y} vertices in the same canonical [0,1] field-fraction coordinates,
-- traced or tapped out on the field, rendered as an open polyline (no
-- fill) instead of a closed polygon. Only needs 2 points (a single
-- segment), not 3.
--
-- Run this entire file in the Supabase SQL Editor AFTER 024.

create table if not exists public.strategy_lines (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.strategy_steps(id) on delete cascade,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  points jsonb not null check (jsonb_typeof(points) = 'array' and jsonb_array_length(points) >= 2),
  color text not null default '#f59e0b',
  -- Same meaning as strategy_highlights.is_straight: a straight-drawn
  -- line's corners are individually draggable, a freehand trace's are not.
  is_straight boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text
);

drop trigger if exists strategy_lines_audit on public.strategy_lines;
create trigger strategy_lines_audit before insert or update on public.strategy_lines
  for each row execute function public.set_audit_fields();

-- Same shape as every other strategy_* table's live policies: plain "true"
-- for every authenticated action (see 024_strategy_highlights.sql's note
-- on this matching what's actually deployed post-017_open_access_for_now.sql).
alter table public.strategy_lines enable row level security;

drop policy if exists "authenticated read" on public.strategy_lines;
create policy "authenticated read" on public.strategy_lines
  for select to authenticated
  using (true);

drop policy if exists "authenticated insert" on public.strategy_lines;
create policy "authenticated insert" on public.strategy_lines
  for insert to authenticated
  with check (true);

drop policy if exists "authenticated update" on public.strategy_lines;
create policy "authenticated update" on public.strategy_lines
  for update to authenticated
  using (true)
  with check (true);

drop policy if exists "authenticated delete" on public.strategy_lines;
create policy "authenticated delete" on public.strategy_lines
  for delete to authenticated
  using (true);

-- Bump the parent play's updated_at when a line changes too (see
-- 018_strategy_play_touch.sql; touch_strategy_play works for any table
-- with a step_id column).
drop trigger if exists strategy_lines_touch_play on public.strategy_lines;
create trigger strategy_lines_touch_play after insert or update or delete on public.strategy_lines
  for each row execute function public.touch_strategy_play();
