-- Membership keyed on user_id, not email: email is a mutable JWT claim,
-- a user id is not. Email survives only as invite addressing (Task 5).
create table if not exists public.team_members (
  id          bigint generated by default as identity primary key,
  team_id     bigint not null references public.organizations(id) on delete cascade,
  user_id     uuid   not null references auth.users(id) on delete cascade,
  role        text   not null default 'member'
                     check (role in ('captain', 'editor', 'member')),
  created_at  timestamptz not null default now(),
  invited_by  uuid references auth.users(id),
  unique (team_id, user_id)
);

create index if not exists team_members_user_id_idx on public.team_members (user_id);
create index if not exists team_members_team_role_idx on public.team_members (team_id, role);

alter table public.team_members enable row level security;

-- A captain-less team is an escalation vector: "this team has no captain"
-- invites a recovery path an attacker can aim at. There is no such path;
-- the last captain simply cannot be removed or demoted.
create or replace function public.enforce_last_captain()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_team_id bigint := coalesce(old.team_id, new.team_id);
  v_remaining int;
begin
  if tg_op = 'UPDATE' and old.role = 'captain' and new.role = 'captain' then
    return new;
  end if;
  if old.role is distinct from 'captain' then
    return coalesce(new, old);
  end if;

  select count(*) into v_remaining
    from public.team_members
   where team_id = v_team_id and role = 'captain' and id <> old.id;

  if v_remaining = 0 then
    raise exception 'team % must have at least one captain', v_team_id;
  end if;
  return coalesce(new, old);
end;
$$;

-- Trigger-only function: Postgres fires it as the table owner regardless
-- of caller privileges, so no role needs (or gets) direct EXECUTE.
revoke all on function public.enforce_last_captain() from public, anon;

create trigger team_members_require_captain
  before update or delete on public.team_members
  for each row execute function public.enforce_last_captain();
