create table if not exists public.team_invites (
  id           bigint generated by default as identity primary key,
  team_id      bigint not null references public.organizations(id) on delete cascade,
  email        text   not null check (email = lower(email)),
  role         text   not null default 'member'
                      check (role in ('editor', 'member')),
  invited_by   uuid references auth.users(id),  -- null: created by migration
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null default now() + interval '30 days',
  accepted_at  timestamptz,
  accepted_by  uuid references auth.users(id)
);

create unique index if not exists team_invites_pending_unique
  on public.team_invites (team_id, email) where accepted_at is null;

create index if not exists team_invites_email_idx
  on public.team_invites (email) where accepted_at is null;

alter table public.team_invites enable row level security;

-- Links answer "whose stats are these", never "what may this person do".
-- No policy anywhere reads this table. Keep it that way.
create table if not exists public.player_links (
  id          bigint generated by default as identity primary key,
  team_id     bigint  not null references public.organizations(id) on delete cascade,
  player_id   integer not null references public.players(id) on delete cascade,
  user_id     uuid    not null references auth.users(id) on delete cascade,
  status      text    not null default 'pending'
                      check (status in ('pending', 'approved')),
  created_at  timestamptz not null default now(),
  unique (player_id),
  unique (team_id, user_id)
);

create index if not exists player_links_user_id_idx on public.player_links (user_id);

alter table public.player_links enable row level security;
