create type public.org_tier as enum ('free', 'plus', 'premium');
create type public.plan_source_type as enum ('stripe', 'employee_grant', 'trial');

alter table public.organizations
  add column if not exists tier public.org_tier not null default 'free',
  add column if not exists trial_ends_at timestamptz not null default (now() + interval '30 days'),
  add column if not exists plan_source public.plan_source_type not null default 'trial',
  add column if not exists is_employee_granted boolean not null default false,
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text;

create table if not exists public.organization_subscriptions (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  stripe_subscription_id text not null,
  status text not null,
  current_period_end timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_usage_logs (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  month_key text not null, -- 'YYYY-MM'
  message_count integer not null default 0,
  unique (organization_id, month_key)
);

alter table public.organization_subscriptions enable row level security;
alter table public.ai_usage_logs enable row level security;

revoke all on public.organization_subscriptions from anon;
revoke all on public.ai_usage_logs from anon;

-- Writes are service-role/admin-helper only: strip the default-privilege
-- write grants from authenticated, then grant back read-only access.
revoke insert, update, delete, truncate on public.organization_subscriptions from authenticated;
revoke insert, update, delete, truncate on public.ai_usage_logs from authenticated;

grant select on public.organization_subscriptions to authenticated;
grant select on public.ai_usage_logs to authenticated;

create policy "authenticated team members select" on public.organization_subscriptions
  for select to authenticated using (organization_id in (select organization_id from public.my_teams()));

create policy "authenticated team members select" on public.ai_usage_logs
  for select to authenticated using (organization_id in (select organization_id from public.my_teams()));

create or replace function public.effective_tier(p_org_id bigint)
returns public.org_tier
language sql
security invoker
set search_path = ''
stable
as $$
  select case
    when o.is_employee_granted then 'premium'::public.org_tier
    when o.plan_source = 'employee_grant' then 'premium'::public.org_tier
    when o.trial_ends_at > now() then 'premium'::public.org_tier
    else o.tier
  end
  from public.organizations o
  where o.id = p_org_id;
$$;
revoke execute on function public.effective_tier(bigint) from public;
grant execute on function public.effective_tier(bigint) to authenticated;
